import {
    DEFAULT,
    DHIS2_CRITICAL_RED,
    DHIS2_DEFAULT_BLACK,
    DHIS2_DISABLED_GRAY,
    DHIS2_SUCCESS_GREEN,
    DHIS2_WARNING_YELLOW,
} from './constants'

/* DATAENTRYBOX ENUMS */
export const STATUS_COLORS = {
    OVERDUE: DHIS2_CRITICAL_RED,
    CLOSEDUE: DHIS2_WARNING_YELLOW,
    NOTCLOSEDUE: DHIS2_DEFAULT_BLACK,
    COMPLETED: DHIS2_SUCCESS_GREEN,
    EXPIRED: DHIS2_DISABLED_GRAY,
    DEFAULT: DEFAULT,
}

export const FORM_STATE = {
    //ACTIVE: 0,
    NOTSET: -1,
    NOTCLOSEDUE: 0,
    CLOSEDUE: 1,
    OVERDUE: 2,
    COMPLETED: 3,
    EXPIRED: 4,
}
